const MD="https://api.mangadex.org", COVER="https://uploads.mangadex.org/covers", AL="https://graphql.anilist.co";
const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const STORE="kyou_manga_v3"; let state=JSON.parse(localStorage.getItem(STORE)||'{"fav":[],"history":[],"bookmarks":{},"reader":{"zoom":100,"dark":true,"double":false}}');
let currentManga=null,currentChapters=[],currentChapterIndex=0,currentPages=0,currentPageSize=0,zoom=state.reader.zoom||100,fit=true;
function save(){localStorage.setItem(STORE,JSON.stringify(state))}
function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2200)}
function setStatus(t){$("#status").textContent=t}
function titleOf(a){return a?.title?.en||Object.values(a?.title||{})[0]||"Untitled"}
function coverOf(m){let r=m.relationships?.find(x=>x.type==="cover_art"),f=r?.attributes?.fileName;return f?`${COVER}/${m.id}/${f}.256.jpg`:(m.coverImage?.large||m.coverImage?.medium||"")}
function descOf(a){return a?.description?.en||Object.values(a?.description||{})[0]||"Deskripsi tidak tersedia."}
async function md(path){let r=await fetch(MD+path,{headers:{Accept:"application/json"}});if(!r.ok)throw Error("MangaDex HTTP "+r.status);return r.json()}
function renderManga(list, source="mangadex"){
 if(!list.length){$("#results").innerHTML='<div class="loading">Tidak ada hasil.</div>';return}
 $("#results").innerHTML=list.map(m=>{let a=m.attributes||m;let title=source==="anilist"?(a.title?.romaji||a.title?.english||a.title?.native):titleOf(a);let img=source==="anilist"?(a.coverImage?.medium||""):coverOf(m);return `<article class="mcard" data-id="${m.id}" data-source="${source}"><img class="cover" loading="lazy" src="${img}" onerror="this.style.opacity=.25"><div class="mcardbody"><div class="mtitle">${esc(title)}</div><div class="msub">${esc(a.status||"Unknown")} · ${esc(a.startDate?.year||a.year||"—")}</div></div></article>`}).join("");
 document.querySelectorAll(".mcard").forEach(c=>c.onclick=()=>c.dataset.source==="anilist"?openAni(c.dataset.id):openManga(c.dataset.id))
}
async function loadPopular(){
 setStatus("Memuat...");
 try{let q=new URLSearchParams({limit:"24"});q.append("includes[]","cover_art");q.set("order[followedCount]","desc");["safe","suggestive"].forEach(x=>q.append("contentRating[]",x));let s=$("#statusFilter").value;if(s)q.append("status[]",s);let d=await md("/manga?"+q);renderManga(d.data||[]);setStatus(`${d.data?.length||0} manga`);$("#sectionTitle").textContent="Manga Populer"}catch(e){$("#results").innerHTML=`<div class="loading">MangaDex gagal diakses. ${esc(e.message)}</div>`;setStatus("")}}
async function search(){
 let q=$("#mSearch").value.trim(); if(!q)return loadPopular();
 let source=$("#source").value;setStatus("Mencari...");$("#sectionTitle").textContent=`Hasil: ${q}`;
 try{
  if(source==="anilist"){let query=`query($q:String){Page(perPage:24){media(search:$q,type:MANGA,sort:POPULARITY_DESC){id title{romaji english native}coverImage{medium}status startDate{year}}}}`;let r=await fetch(AL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query,variables:{q}})});let d=await r.json();renderManga(d.data?.Page?.media||[],"anilist");setStatus(`${d.data?.Page?.media?.length||0} hasil • AniList`)}
  else{let p=new URLSearchParams({title:q,limit:"24"});p.append("includes[]","cover_art");let s=$("#statusFilter").value;if(s)p.append("status[]",s);let sort=$("#sortFilter").value;if(sort==="latest")p.set("order[latestUploadedChapter]","desc");if(sort==="title")p.set("order[title]","asc");else p.set("order[relevance]","desc");let d=await md("/manga?"+p);renderManga(d.data||[]);setStatus(`${d.data?.length||0} hasil`)}
 }catch(e){$("#results").innerHTML=`<div class="loading">Pencarian gagal. ${esc(e.message)}</div>`;setStatus("")}}
async function openAni(id){
 $("#detailModal").classList.remove("hidden");$("#detail").innerHTML='<div class="loading">Memuat metadata AniList...</div>';
 try{let q=`query($id:Int){Media(id:$id,type:MANGA){id title{romaji english native}description status chapters volumes genres averageScore startDate{year}coverImage{large}siteUrl}}`;let r=await fetch(AL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:q,variables:{id:+id}})});let m=(await r.json()).data.Media;$("#detail").innerHTML=`<div class="detail-grid"><img class="detail-cover" src="${m.coverImage?.large||""}"><div class="detail"><h2>${esc(m.title.english||m.title.romaji||m.title.native)}</h2><div class="detail-alt">AniList · ${esc(m.status||"")} · Score ${esc(m.averageScore||"—")}</div><p class="detail-desc">${esc((m.description||"").replace(/<[^>]+>/g,"")).slice(0,1600)}</p><div class="tags">${(m.genres||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join("")}</div><button class="primary" onclick="searchMangaDex(${JSON.stringify(m.title.romaji||m.title.english||"")})">🔎 Cari versi MangaDex</button></div></div>`}catch(e){$("#detail").innerHTML=`<div class="loading">AniList gagal. ${esc(e.message)}</div>`}}
window.searchMangaDex=q=>{$("#detailModal").classList.add("hidden");$("#source").value="mangadex";$("#mSearch").value=q;search()}
async function openManga(id){
 $("#detailModal").classList.remove("hidden");$("#detail").innerHTML='<div class="loading">Memuat detail...</div>';
 try{let m=(await md(`/manga/${id}?includes[]=cover_art`)).data;currentManga=m;let a=m.attributes||{},author=m.relationships?.find(x=>x.type==="author")?.attributes?.name||"Unknown";
 $("#detail").innerHTML=`<div class="detail-grid"><img class="detail-cover" src="${coverOf(m)}"><div class="detail"><h2>${esc(titleOf(a))}</h2><div class="detail-alt">${esc(author)} · ${esc(a.status||"")}</div><p class="detail-desc">${esc(descOf(a)).slice(0,1600)}</p><div class="tags">${(a.tags||[]).slice(0,14).map(t=>`<span class="tag">${esc(t.attributes?.name?.en||"")}</span>`).join("")}</div><button class="primary" id="favManga">${state.fav.includes(id)?"♥ Hapus Favorit":"♡ Tambah Favorit"}</button><div class="chapters"><h3>Chapter</h3><div id="chapters">Memuat...</div></div></div></div>`;
 $("#favManga").onclick=()=>toggleFav(id);await loadChapters(id)
 }catch(e){$("#detail").innerHTML=`<div class="loading">Gagal memuat detail: ${esc(e.message)}</div>`}}
async function loadChapters(id){
 try{let lang=$("#language").value,p=new URLSearchParams({limit:"500"});p.append("order[chapter]","desc");p.append("includes[]","scanlation_group");if(lang!=="all")p.append("translatedLanguage[]",lang);let d=await md(`/manga/${id}/feed?${p}`);currentChapters=(d.data||[]).sort((x,y)=>((+y.attributes?.chapter||-1)-(+x.attributes?.chapter||-1)));let c=$("#chapters");
 if(!currentChapters.length){c.innerHTML=`<div class="loading">Tidak ada chapter ${lang==="id"?"Bahasa Indonesia":lang==="en"?"Bahasa Inggris":"yang tersedia"}.</div>`;return}
 c.innerHTML=currentChapters.map((ch,i)=>{let a=ch.attributes||{};return `<button class="chapter" data-ch="${ch.id}"><span>Chapter ${esc(a.chapter||"?")} ${a.title?"— "+esc(a.title):""}</span><small>${a.translatedLanguage==="id"?"🇮🇩 Indonesia":a.translatedLanguage==="en"?"🇬🇧 English":a.translatedLanguage}</small></button>`}).join("");
 c.querySelectorAll("[data-ch]").forEach(b=>b.onclick=()=>openChapter(b.dataset.ch))
 }catch(e){$("#chapters").innerHTML=`<div class="loading">Gagal memuat chapter.</div>`}}
function toggleFav(id){state.fav.includes(id)?state.fav=state.fav.filter(x=>x!==id):state.fav.push(id);save();toast(state.fav.includes(id)?"Ditambahkan ke favorit":"Dihapus dari favorit");if(currentManga)$("#favManga").textContent=state.fav.includes(id)?"♥ Hapus Favorit":"♡ Tambah Favorit"}
async function openChapter(id){
 let i=currentChapters.findIndex(c=>c.id===id);if(i<0)return;currentChapterIndex=i;$("#detailModal").classList.add("hidden");$("#reader").classList.remove("hidden");await renderChapter()}
async function renderChapter(){
 let ch=currentChapters[currentChapterIndex];if(!ch)return;let a=ch.attributes||{}, key=`${currentManga.id}:${ch.id}`;$("#readerTitle").textContent=`${titleOf(currentManga.attributes)} · Ch. ${a.chapter||"?"} · ${a.translatedLanguage==="id"?"🇮🇩":"🇬🇧"}`;$("#chapterSelect").innerHTML=currentChapters.map((x,i)=>`<option value="${i}" ${i===currentChapterIndex?"selected":""}>Ch. ${esc(x.attributes?.chapter||"?")} · ${x.attributes?.translatedLanguage||""}</option>`).join("");$("#pages").innerHTML='<div class="loading">Memuat halaman...</div>';
 try{let d=await md(`/at-home/server/${ch.id}`),hash=d.chapter?.hash,files=d.chapter?.data||[];if(!hash||!files.length)throw Error("No pages");currentPages=files.length;currentPageSize=0;$("#pages").innerHTML=files.map((f,i)=>`<img class="page" data-page="${i}" loading="lazy" src="${d.baseUrl}/data/${hash}/${encodeURIComponent(f)}" alt="Page ${i+1}">`).join("");state.history=[{manga:currentManga.id,title:titleOf(currentManga.attributes),chapter:ch.id,chapterNo:a.chapter||"?"},...state.history.filter(x=>x.manga!==currentManga.id)].slice(0,30);save();applyReader();$("#pages").scrollTop=0;observePages()}catch(e){$("#pages").innerHTML=`<div class="loading">Chapter tidak bisa dimuat. ${esc(e.message)}</div>`}}
function observePages(){let ob=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){let i=+e.target.dataset.page;state.bookmarks[`${currentManga.id}:${currentChapters[currentChapterIndex].id}`]=i;save();$("#readerProgress").textContent=Math.round((i+1)/currentPages*100)+"%"}})},{root:$("#pages"),threshold:.55});document.querySelectorAll(".page").forEach(p=>ob.observe(p))}
function applyReader(){document.body.classList.toggle("reader-dark",state.reader.dark);document.documentElement.style.setProperty("--reader-zoom",(fit?100:zoom)+"%");$("#zoomValue").textContent=(fit?100:zoom)+"%"}
function showHistory(){if(!state.history.length){$("#results").innerHTML='<div class="loading">Belum ada riwayat.</div>';return}$("#sectionTitle").textContent="Riwayat Baca";$("#results").innerHTML=state.history.map(x=>`<article class="history-item"><b>${esc(x.title)}</b><span>Chapter ${esc(x.chapterNo)}</span><button data-hist="${x.manga}">Buka</button></article>`).join("");document.querySelectorAll("[data-hist]").forEach(b=>b.onclick=()=>openManga(b.dataset.hist))}
function showFavorites(){let ids=state.fav;if(!ids.length){$("#results").innerHTML='<div class="loading">Belum ada favorit.</div>';return}$("#sectionTitle").textContent="Favorit";setStatus(`${ids.length} tersimpan`);Promise.all(ids.map(id=>md(`/manga/${id}?includes[]=cover_art`).then(x=>x.data).catch(()=>null))).then(xs=>renderManga(xs.filter(Boolean)))}
$("#searchBtn").onclick=search;$("#mSearch").addEventListener("keydown",e=>e.key==="Enter"&&search());$("#trendingBtn").onclick=loadPopular;$("#historyBtn").onclick=showHistory;$("#favBtn").onclick=showFavorites;$("#settingsBtn").onclick=()=>$("#readerModal").classList.remove("hidden");$("#readerSettings").onclick=()=>$("#readerModal").classList.remove("hidden");
$("#language").onchange=()=>currentManga&&loadChapters(currentManga.id);$("#source").onchange=search;$("#statusFilter").onchange=()=>$("#mSearch").value.trim()?search():loadPopular();$("#sortFilter").onchange=search;
$("#randomBtn").onclick=async()=>{let p=new URLSearchParams({limit:"1"});p.append("includes[]","cover_art");p.set("order[followedCount]","desc");let d=await md("/manga?"+p);if(d.data?.[0])openManga(d.data[0].id)};
$("[data-close]").onclick=()=>$("#detailModal").classList.add("hidden");document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest(".modal").classList.add("hidden"));
$("#closeReader").onclick=()=>$("#reader").classList.add("hidden");$("#chapterSelect").onchange=e=>{currentChapterIndex=+e.target.value;renderChapter()};$("#prevChapter").onclick=()=>{if(currentChapterIndex<currentChapters.length-1){currentChapterIndex++;renderChapter()}};$("#nextChapter").onclick=()=>{if(currentChapterIndex>0){currentChapterIndex--;renderChapter()}};
$("#zoomIn").onclick=()=>{fit=false;zoom=Math.min(180,zoom+10);state.reader.zoom=zoom;save();applyReader()};$("#zoomOut").onclick=()=>{fit=false;zoom=Math.max(50,zoom-10);state.reader.zoom=zoom;save();applyReader()};$("#fitBtn").onclick=()=>{fit=!fit;applyReader()};$("#bookmarkPage").onclick=()=>toast("Posisi baca tersimpan otomatis");$("#saveReader").onclick=()=>{$("#darkReader").checked&&(state.reader.dark=true);state.reader.dark=$("#darkReader").checked;state.reader.double=$("#doublePage").checked;save();$("#readerModal").classList.add("hidden");applyReader()};
document.addEventListener("keydown",e=>{if($("#reader").classList.contains("hidden"))return;if(e.key==="Escape")$("#reader").classList.add("hidden");if(e.key==="ArrowLeft")$("#prevChapter").click();if(e.key==="ArrowRight")$("#nextChapter").click();if(e.key==="+")$("#zoomIn").click();if(e.key==="-")$("#zoomOut").click()});
$("#darkReader").checked=state.reader.dark;$("#doublePage").checked=state.reader.double;loadPopular();